apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    tad.gitops.set/image: ".spec.template.spec.containers[0].image"
    tad.gitops.get/image: ".spec.template.spec.containers[0].image"
    tad.gitops.set/replicas: ".spec.replicas"
    tad.gitops.get/replicas: ".spec.replicas"
  name: hpo16kkon-java-springboot
spec:
  replicas: 1
  template:
    spec:
      containers:
        - image: quay.io/rhtap_qe/rhtap-qe-java-springboot:01ee54c5907cbd157e82a7c1f162bce48f5129b9@sha256:bb001ecbdc01a2fa9566f99a4f78661c9fbb64ae3244bc4a4092f17e5c47e5f9
          name: container-image
